package pizza;

class PizzaData extends sds.MessageHeaderData
{
    string cheese;
    string tomatoSauce;

    /* hej hopp */
    //@version = 1 .. 5 //@version = 10
    //@range = 0 .. 1023
    int Kalle;

    pizza.extra.Secret sec;

    enum ResWord {if, begin, None};
    ResWord enum_var;
}
