name: XML-test

on:
  push:
    branches:
      - xmltest
    paths-ignore:
      - 'Ada/**'
      - 'CSharp/**'
      - 'Delphi/**'
      - 'Doc/**'
      - 'Python/**'
      - 'Scripts/**'
      - 'Syntax*/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      #- name: list environment
      #  run: env
      #- name: cmake version
      #  run: cmake --version
      - name: TinyXML2 Get
        run: git clone https://github.com/leethomason/tinyxml2.git $HOME/tinyxml2
      - name: TinyXML2 Build
        run: pushd $HOME/tinyxml2 && mkdir mybuild && cd mybuild && CCXFLAGS=-fPIC cmake -DCMAKE_INSTALL_PREFIX=$HOME/tinyxml2/deploy .. && make install && popd
      #
      - name: GTest Get
        run: git clone https://github.com/google/googletest/ $HOME/gtest
      - name: GTest Build
        run: pushd $HOME/gtest && mkdir mybuild && cd mybuild && cmake -DCMAKE_INSTALL_PREFIX=$HOME/gtest/deploy .. && make install && popd
      - name: GTest Set GOOGLETEST_HOME
        run: echo "GOOGLETEST_HOME=$HOME/gtest/deploy" >> $GITHUB_ENV
      #- name: debug
      #  run: ls -alR $GOOGLETEST_HOME
      - name: CppCheck Install
        run: sudo apt-get install cppcheck
      #
      - name: boost Install
        run: sudo apt-get install libboost-system-dev libboost-thread-dev libboost-regex-dev libboost-filesystem-dev libboost-date-time-dev
      #- name: Set BOOST_HOME
      #  run: echo "BOOST_HOME=$BOOST_ROOT_1_72_0" >> $GITHUB_ENV
      - name: Build
        run: make BOOST_ARCH=-x64 CXXSTANDARD=14 TINYXML2_INSTALL_DIR=$HOME/tinyxml2/deploy
        env:
          MAKEFLAGS: "-j2"
      - name: Run C++ Tests
        run: make CXXSTANDARD=14 unittest-c++
      - name: CppCheck Analysis
        run: cppcheck --enable=all Cpp/source Cpp/include > /dev/null
